name: Workflow with Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Check code
        uses: actions/checkout@v2

      # Step 2: Run a script and pass the secret as an environment variable
      - name: Run script with API key
        run: node your-script.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
